#!/usr/bin/env python3
"""Register Dart plugins as a generated package in $KLANGK_PLUGINS_DIR/.dart/.

Scans $KLANGK_PLUGINS_DIR/*/klangk/pubspec.yaml for plugins with Dart packages
and generates:

  $KLANGK_PLUGINS_DIR/.dart/pubspec.yaml         — package with path deps
  $KLANGK_PLUGINS_DIR/.dart/lib/klangk_plugins.dart — createAllPlugins()
  $KLANGK_PLUGINS_DIR/.dart/pubspec_overrides.yaml — real path override

Also creates a symlink at src/frontend/pubspec_overrides.yaml pointing
to the generated overrides file, so Flutter resolves the klangk_plugins
placeholder dependency to the actual package. No committed source files
are modified.
"""

import os
import re

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PLUGINS_DIR = os.environ.get("KLANGK_PLUGINS_DIR") or os.path.join(
    os.path.expanduser("~"), ".klangk", "plugins"
)
KLANGK_DART_PLUGINS_PKG = os.path.join(PLUGINS_DIR, ".dart")
PUBSPEC = os.path.join(KLANGK_DART_PLUGINS_PKG, "pubspec.yaml")
OUTPUT = os.path.join(KLANGK_DART_PLUGINS_PKG, "lib", "klangk_plugins.dart")

PLUGIN_API_DEP = {
    "bark_plugin_api": {"git": {"url": "https://github.com/mcdonc/bark-plugin-api.git"}}
}


def find_plugins():
    """Scan plugins/*/klangk/ for Dart packages, return metadata."""
    plugins = []
    if not os.path.isdir(PLUGINS_DIR):
        return plugins

    for name in sorted(os.listdir(PLUGINS_DIR)):
        plugin_dir = os.path.join(PLUGINS_DIR, name)
        dart_dir = os.path.join(plugin_dir, "klangk")
        pubspec_file = os.path.join(dart_dir, "pubspec.yaml")
        plugin_dart = os.path.join(dart_dir, "lib", "plugin.dart")

        if not os.path.isfile(pubspec_file) or not os.path.isfile(plugin_dart):
            continue

        with open(pubspec_file) as f:
            pubspec = yaml.safe_load(f)

        package_name = pubspec.get("name", f"klangk_plugin_{name}")

        with open(plugin_dart) as f:
            source = f.read()

        matches = re.findall(r"class\s+(\w+)\s+extends\s+ToolPlugin", source)
        if not matches:
            continue

        for class_name in matches:
            plugins.append(
                {
                    "name": name,
                    "package_name": package_name,
                    "dart_dir": dart_dir,
                    "class_name": class_name,
                }
            )

    return plugins


def write_pubspec(plugins):
    """Generate $KLANGK_PLUGINS_DIR/.dart/pubspec.yaml with plugin path dependencies."""
    deps = {
        "flutter": {"sdk": "flutter"},
    }
    deps.update(PLUGIN_API_DEP)

    seen = set()
    for p in plugins:
        if p["package_name"] not in seen:
            deps[p["package_name"]] = {"path": p["dart_dir"]}
            seen.add(p["package_name"])

    pubspec = {
        "name": "klangk_plugins",
        "publish_to": "none",
        "version": "0.0.1",
        "environment": {"sdk": "^3.6.0", "flutter": "^3.27.0"},
        "dependencies": deps,
    }

    os.makedirs(os.path.dirname(PUBSPEC), exist_ok=True)
    with open(PUBSPEC, "w") as f:
        yaml.dump(pubspec, f, default_flow_style=False, sort_keys=False)


def generate_dart(plugins):
    """Generate klangk_plugins.dart with package imports."""
    lines = [
        "// GENERATED by import_dart_plugins.py — do not edit.",
        "import 'package:bark_plugin_api/bark_plugin_api.dart';",
        "",
    ]
    for p in plugins:
        lines.append(f"import 'package:{p['package_name']}/plugin.dart';")

    lines.append("")
    lines.append("List<ToolPlugin> createAllPlugins() {")
    lines.append("  return [")
    for p in plugins:
        lines.append(f"    {p['class_name']}(),")
    lines.append("  ];")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def write_overrides_and_symlink():
    """Write pubspec_overrides.yaml at ~/.klangk/klangk/ and symlink it
    into the frontend directory so Flutter can find it."""
    overrides_content = f"dependency_overrides:\n  klangk_plugins:\n    path: {KLANGK_DART_PLUGINS_PKG}\n"
    overrides_path = os.path.join(KLANGK_DART_PLUGINS_PKG, "pubspec_overrides.yaml")
    with open(overrides_path, "w") as f:
        f.write(overrides_content)

    # Symlink into the frontend directory
    frontend_dir = os.path.join(ROOT, "src", "frontend")
    symlink_path = os.path.join(frontend_dir, "pubspec_overrides.yaml")
    if os.path.islink(symlink_path) or os.path.exists(symlink_path):
        os.remove(symlink_path)
    os.symlink(overrides_path, symlink_path)


def main():
    plugins = find_plugins()

    write_pubspec(plugins)
    write_overrides_and_symlink()

    output = generate_dart(plugins)
    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, "w") as f:
        f.write(output)

    names = [p["class_name"] for p in plugins]
    print(f"Generated Dart {PUBSPEC} with {len(plugins)} plugin(s)")
    print(f"Generated Dart {OUTPUT}: {', '.join(names) or '(none)'}")


if __name__ == "__main__":
    main()
