#!/usr/bin/env bash
# Create a stub bark_plugins package so flutter pub get works without
# running the full import_dart_plugins.py codegen. Useful for CI and
# first-time checkouts before plugins are fetched.
#
# Skips if pubspec_overrides.yaml already exists (real plugins are set up).
set -euo pipefail

FRONTEND_DIR="$(cd "$(dirname "$0")/../src/frontend" && pwd)"

if [ -e "$FRONTEND_DIR/pubspec_overrides.yaml" ]; then
  exit 0
fi

PLUGINS_DIR="${BARK_PLUGINS_DIR:-$HOME/.bark/plugins}"
STUB_DIR="$PLUGINS_DIR/.dart"
mkdir -p "$STUB_DIR/lib"

cat >"$STUB_DIR/pubspec.yaml" <<'EOF'
name: bark_plugins
publish_to: none
version: 0.0.1
environment:
  sdk: ^3.6.0
  flutter: ^3.27.0
dependencies:
  flutter:
    sdk: flutter
  bark_plugin_api:
    git:
      url: https://github.com/mcdonc/bark-plugin-api.git
EOF

cat >"$STUB_DIR/lib/bark_plugins.dart" <<'EOF'
// Stub — no plugins. Generated by scripts/stub_dart_plugins.sh
import 'package:bark_plugin_api/bark_plugin_api.dart';
List<ToolPlugin> createAllPlugins() => [];
EOF

# Write overrides file and symlink into frontend
OVERRIDES="$STUB_DIR/pubspec_overrides.yaml"
cat >"$OVERRIDES" <<EOF
dependency_overrides:
  bark_plugins:
    path: $STUB_DIR
EOF
ln -sf "$OVERRIDES" "$FRONTEND_DIR/pubspec_overrides.yaml"

echo "Created stub bark_plugins at $STUB_DIR"
