name: Cleanup Runs

on:
  schedule:
    # 6am and 6pm EST (11am and 11pm UTC)
    - cron: "0 11,23 * * *"
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
          delete_run_by_conclusion_pattern: "skipped,cancelled"
